name: Publish Docker Image
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
    - master

    # Publish `v1.2.3` tags as releases.
    tags:
    - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: jgoodhouse/openhab-templatizer

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: jgoodhouse
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm,linux/386
        push: true
        tags: $IMAGE_NAME:latest
